<a href="https://colab.research.google.com/github/napchick/project/blob/main/project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Задача

В данном задании нам предоставлена информация об [энергопотреблении зданий в Нью-Йорке](https://www1.nyc.gov/html/gbee/html/plan/ll84_scores.shtml).

Наша цель — предсказать рейтинг энергопотребления здания (Energy Star Score).

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/ddvika/DS_2021/main/lecture_2/Energy_consumption_NY.csv')
data.head()

,Order,Property Id,Property Name,Parent Property Id,Parent Property Name,BBL - 10 digits,"NYC Borough, Block and Lot (BBL) self-reported",NYC Building Identification Number (BIN),Address 1 (self-reported),Address 2,...,Source EUI (kBtu/ft²),Release Date,Water Required?,DOF Benchmarking Submission Status,Latitude,Longitude,Community Board,Council District,Census Tract,NTA
0,1,13286,201/205,13286,201/205,1013160001,1013160001,1037549,201/205 East 42nd st.,Not Available,...,619.4,05/01/2017 05:32:03 PM,No,In Compliance,40.750791,-73.973963,6.0,4.0,88.0,Turtle Bay-East Midtown ...
1,2,28400,NYP Columbia (West Campus),28400,NYP Columbia (West Campus),1021380040,1-02138-0040,1084198; 1084387;1084385; 1084386; 1084388; 10...,622 168th Street,Not Available,...,404.3,04/27/2017 11:23:27 AM,No,In Compliance,40.841402,-73.942568,12.0,10.0,251.0,Washington Heights South ...
2,3,4778226,MSCHoNY North,28400,NYP Columbia (West Campus),1021380030,1-02138-0030,1063380,3975 Broadway,Not Available,...,Not Available,04/27/2017 11:23:27 AM,No,In Compliance,40.840427,-73.940249,12.0,10.0,251.0,Washington Heights South ...
3,4,4778267,Herbert Irving Pavilion & Millstein Hospital,28400,NYP Columbia (West Campus),1021390001,1-02139-0001,1087281; 1076746,161 Fort Washington Ave,177 Fort Washington Ave,...,Not Available,04/27/2017 11:23:27 AM,No,In Compliance,40.840746,-73.942854,12.0,10.0,255.0,Washington Heights South ...
4,5,4778288,Neuro Institute,28400,NYP Columbia (West Campus),1021390085,1-02139-0085,1063403,710 West 168th Street,Not Available,...,Not Available,04/27/2017 11:23:27 AM,No,In Compliance,40.841559,-73.942528,12.0,10.0,255.0,Washington Heights South ...

In [3]:
data.shape

(11746, 60)

## 1.  EDA

### 1.0 Изучение данных

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11746 entries, 0 to 11745
Data columns (total 60 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Order                                                       11746 non-null  int64
 1   Property Id                                                 11746 non-null  int64
 2   Property Name                                               11746 non-null  object
 3   Parent Property Id                                          11746 non-null  object
 4   Parent Property Name                                        11746 non-null  object
 5   BBL - 10 digits                                             11735 non-null  object
 6   NYC Borough, Block and Lot (BBL) self-reported              11746 non-null  object
 7   NYC Building Identification Number (BIN)                    11746 non-null  object
 8   Address 1 (self-reported)                                   11746 non-null  object
 9   Address 2                                                   11746 non-null  object
 10  Postal Code                                                 11746 non-null  object
 11  Street Number                                               11622 non-null  object
 12  Street Name                                                 11624 non-null  object
 13  Borough                                                     11628 non-null  object
 14  DOF Gross Floor Area                                        11628 non-null  float64
 15  Primary Property Type - Self Selected                       11746 non-null  object
 16  List of All Property Use Types at Property                  11746 non-null  object
 17  Largest Property Use Type                                   11746 non-null  object
 18  Largest Property Use Type - Gross Floor Area (ft²)          11746 non-null  object
 19  2nd Largest Property Use Type                               11746 non-null  object
 20  2nd Largest Property Use - Gross Floor Area (ft²)           11746 non-null  object
 21  3rd Largest Property Use Type                               11746 non-null  object
 22  3rd Largest Property Use Type - Gross Floor Area (ft²)      11746 non-null  object
 23  Year Built                                                  11746 non-null  int64
 24  Number of Buildings - Self-reported                         11746 non-null  int64
 25  Occupancy                                                   11746 non-null  int64
 26  Metered Areas (Energy)                                      11746 non-null  object
 27  Metered Areas  (Water)                                      11746 non-null  object
 28  ENERGY STAR Score                                           11746 non-null  object
 29  Site EUI (kBtu/ft²)                                         11746 non-null  object
 30  Weather Normalized Site EUI (kBtu/ft²)                      11746 non-null  object
 31  Weather Normalized Site Electricity Intensity (kWh/ft²)     11746 non-null  object
 32  Weather Normalized Site Natural Gas Intensity (therms/ft²)  11746 non-null  object
 33  Weather Normalized Source EUI (kBtu/ft²)                    11746 non-null  object
 34  Fuel Oil #1 Use (kBtu)                                      11746 non-null  object
 35  Fuel Oil #2 Use (kBtu)                                      11746 non-null  object
 36  Fuel Oil #4 Use (kBtu)                                      11746 non-null  object
 37  Fuel Oil #5 & 6 Use (kBtu)                                  11746 non-null  object
 38  Diesel #2 Use (kBtu)                                        11746 non-null  object
 39  District Steam Use (kBtu)                                   11746 non-null  object
 40  Natural Gas Use (kBtu)                                      11746 non-null  object
 41  Weather Normalized Site Natural Gas Use (therms)            11746 non-null  object
 42  Electricity Use - Grid Purchase (kBtu)                      11746 non-null  object
 43  Weather Normalized Site Electricity (kWh)                   11746 non-null  object
 44  Total GHG Emissions (Metric Tons CO2e)                      11746 non-null  object
 45  Direct GHG Emissions (Metric Tons CO2e)                     11746 non-null  object
 46  Indirect GHG Emissions (Metric Tons CO2e)                   11746 non-null  object
 47  Property GFA - Self-Reported (ft²)                          11746 non-null  int64
 48  Water Use (All Water Sources) (kgal)                        11746 non-null  object
 49  Water Intensity (All Water Sources) (gal/ft²)               11746 non-null  object
 50  Source EUI (kBtu/ft²)                                       11746 non-null  object
 51  Release Date                                                11746 non-null  object
 52  Water Required?                                             11628 non-null  object
 53  DOF Benchmarking Submission Status                          11716 non-null  object
 54  Latitude                                                    9483 non-null   float64
 55  Longitude                                                   9483 non-null   float64
 56  Community Board                                             9483 non-null   float64
 57  Council District                                            9483 non-null   float64
 58  Census Tract                                                9483 non-null   float64
 59  NTA                                                         9483 non-null   object
dtypes: float64(6), int64(6), object(48)
memory usage: 5.4+ MB

#### Как мы видим, большинство признаков, даже числовые, имеет тип данных object. Это будет проблемой для наших моделей, поэтому такие признаки(числовые) надо привести к float или int

In [5]:
#для того, чтобы мы могли привести нужные столбцы к int или float необходимо строку "Not Available" поменять на np.nan
data = data.replace({'Not Available': np.nan})

In [6]:
for col in list(data.columns):
    try:
        data[col] = data[col].astype(float)
    except Exception:
        print(f"Признак {col} не может быть преобразован в float")

Признак Property Name не может быть преобразован в float
Признак Parent Property Id не может быть преобразован в float
Признак Parent Property Name не может быть преобразован в float
Признак BBL - 10 digits не может быть преобразован в float
Признак NYC Borough, Block and Lot (BBL) self-reported не может быть преобразован в float
Признак NYC Building Identification Number (BIN) не может быть преобразован в float
Признак Address 1 (self-reported) не может быть преобразован в float
Признак Address 2 не может быть преобразован в float
Признак Postal Code не может быть преобразован в float
Признак Street Number не может быть преобразован в float
Признак Street Name не может быть преобразован в float
Признак Borough не может быть преобразован в float
Признак Primary Property Type - Self Selected не может быть преобразован в float
Признак List of All Property Use Types at Property не может быть преобразован в float
Признак Largest Property Use Type не может быть преобразован в float
Признак 2nd Largest Property Use Type не может быть преобразован в float
Признак 3rd Largest Property Use Type не может быть преобразован в float
Признак Metered Areas (Energy) не может быть преобразован в float
Признак Metered Areas  (Water) не может быть преобразован в float
Признак Release Date не может быть преобразован в float
Признак Water Required? не может быть преобразован в float
Признак DOF Benchmarking Submission Status не может быть преобразован в float
Признак NTA не может быть преобразован в float

#### Проверим типы данных

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11746 entries, 0 to 11745
Data columns (total 60 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Order                                                       11746 non-null  float64
 1   Property Id                                                 11746 non-null  float64
 2   Property Name                                               11746 non-null  object
 3   Parent Property Id                                          11746 non-null  object
 4   Parent Property Name                                        11746 non-null  object
 5   BBL - 10 digits                                             11735 non-null  object
 6   NYC Borough, Block and Lot (BBL) self-reported              11735 non-null  object
 7   NYC Building Identification Number (BIN)                    11584 non-null  object
 8   Address 1 (self-reported)                                   11746 non-null  object
 9   Address 2                                                   207 non-null    object
 10  Postal Code                                                 11746 non-null  object
 11  Street Number                                               11622 non-null  object
 12  Street Name                                                 11624 non-null  object
 13  Borough                                                     11628 non-null  object
 14  DOF Gross Floor Area                                        11628 non-null  float64
 15  Primary Property Type - Self Selected                       11746 non-null  object
 16  List of All Property Use Types at Property                  11746 non-null  object
 17  Largest Property Use Type                                   11744 non-null  object
 18  Largest Property Use Type - Gross Floor Area (ft²)          11744 non-null  float64
 19  2nd Largest Property Use Type                               3741 non-null   object
 20  2nd Largest Property Use - Gross Floor Area (ft²)           3741 non-null   float64
 21  3rd Largest Property Use Type                               1484 non-null   object
 22  3rd Largest Property Use Type - Gross Floor Area (ft²)      1484 non-null   float64
 23  Year Built                                                  11746 non-null  float64
 24  Number of Buildings - Self-reported                         11746 non-null  float64
 25  Occupancy                                                   11746 non-null  float64
 26  Metered Areas (Energy)                                      11689 non-null  object
 27  Metered Areas  (Water)                                      7137 non-null   object
 28  ENERGY STAR Score                                           9642 non-null   float64
 29  Site EUI (kBtu/ft²)                                         11583 non-null  float64
 30  Weather Normalized Site EUI (kBtu/ft²)                      10281 non-null  float64
 31  Weather Normalized Site Electricity Intensity (kWh/ft²)     10959 non-null  float64
 32  Weather Normalized Site Natural Gas Intensity (therms/ft²)  9783 non-null   float64
 33  Weather Normalized Source EUI (kBtu/ft²)                    10281 non-null  float64
 34  Fuel Oil #1 Use (kBtu)                                      9 non-null      float64
 35  Fuel Oil #2 Use (kBtu)                                      2581 non-null   float64
 36  Fuel Oil #4 Use (kBtu)                                      1321 non-null   float64
 37  Fuel Oil #5 & 6 Use (kBtu)                                  594 non-null    float64
 38  Diesel #2 Use (kBtu)                                        16 non-null     float64
 39  District Steam Use (kBtu)                                   936 non-null    float64
 40  Natural Gas Use (kBtu)                                      10304 non-null  float64
 41  Weather Normalized Site Natural Gas Use (therms)            9784 non-null   float64
 42  Electricity Use - Grid Purchase (kBtu)                      11502 non-null  float64
 43  Weather Normalized Site Electricity (kWh)                   10960 non-null  float64
 44  Total GHG Emissions (Metric Tons CO2e)                      11672 non-null  float64
 45  Direct GHG Emissions (Metric Tons CO2e)                     11663 non-null  float64
 46  Indirect GHG Emissions (Metric Tons CO2e)                   11681 non-null  float64
 47  Property GFA - Self-Reported (ft²)                          11746 non-null  float64
 48  Water Use (All Water Sources) (kgal)                        7762 non-null   float64
 49  Water Intensity (All Water Sources) (gal/ft²)               7762 non-null   float64
 50  Source EUI (kBtu/ft²)                                       11583 non-null  float64
 51  Release Date                                                11746 non-null  object
 52  Water Required?                                             11628 non-null  object
 53  DOF Benchmarking Submission Status                          11716 non-null  object
 54  Latitude                                                    9483 non-null   float64
 55  Longitude                                                   9483 non-null   float64
 56  Community Board                                             9483 non-null   float64
 57  Council District                                            9483 non-null   float64
 58  Census Tract                                                9483 non-null   float64
 59  NTA                                                         9483 non-null   object
dtypes: float64(37), object(23)
memory usage: 5.4+ MB

#### Теперь, когда мы разобрались с типами данных наших признаков, можно начать работать с пропусками

### 1.1. Работа с пропусками

#### Посмотрим процент пропусков в каждом столбце

In [8]:
count_of_missings = pd.DataFrame(data=(data.isna().sum() / len(data)).round(2), columns = ['% of total values'])

In [9]:
count_of_missings.sort_values(by=['% of total values'], ascending = False).head(5)

                            % of total values
Fuel Oil #1 Use (kBtu)                   1.00
Diesel #2 Use (kBtu)                     1.00
Address 2                                0.98
Fuel Oil #5 & 6 Use (kBtu)               0.95
District Steam Use (kBtu)                0.92

#### Как мы видим, у нас есть признаки с очень большим количеством пропусков(>50%). Такие признаки стоит убрать

In [10]:
bad_features = list(count_of_missings[count_of_missings['% of total values'] > 0.5].index)

In [11]:
bad_features

['Address 2',
 '2nd Largest Property Use Type',
 '2nd Largest Property Use - Gross Floor Area (ft²)',
 '3rd Largest Property Use Type',
 '3rd Largest Property Use Type - Gross Floor Area (ft²)',
 'Fuel Oil #1 Use (kBtu)',
 'Fuel Oil #2 Use (kBtu)',
 'Fuel Oil #4 Use (kBtu)',
 'Fuel Oil #5 & 6 Use (kBtu)',
 'Diesel #2 Use (kBtu)',
 'District Steam Use (kBtu)']

In [12]:
data.drop(columns=bad_features, inplace = True)

In [13]:
#Сделаем маску для того, чтобы можно было отдельно работать с вещественными и не вещественными признаками
cat_features = (data.dtypes == object).values

In [14]:
# Датасет с вещественными признаками
data_real = data[data.columns[~cat_features]]

In [15]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [16]:
myImputer=IterativeImputer()
myImputer.fit(data_real)
myImputer_data = myImputer.transform(data_real)

In [17]:
#заполняем пропуски в вещественных столбцах
myImputer_data = pd.DataFrame(myImputer_data,columns = data_real.columns)

In [18]:
# Датасет с категореальными и порядковыми признаками
data_cat = data[data.columns[cat_features]]

In [19]:
# Заменяем пропуски на пустые строки
data_cat = data_cat.fillna("")

In [20]:
# Соединим получившиеся датасеты
data_without_missing = pd.concat([myImputer_data, data_cat], axis=1)

In [21]:
# Проверяем на наличие пропусков
data_without_missing.isna().any().any()

False

In [22]:
data_without_missing.shape

(11746, 49)

In [23]:
# Разобьем наши данные на признаковое описание и целевую переменную
X = data_without_missing.drop('ENERGY STAR Score', axis = 1)
y = data_without_missing['ENERGY STAR Score'][X.index]

### 1.2 Преобразование нечисловых признаков

In [24]:
from sklearn.preprocessing import OneHotEncoder

In [25]:
ohe = OneHotEncoder()
ohe.fit(X)
X_cat = ohe.transform(X)

In [26]:
X_U = pd.DataFrame(data = X_cat.toarray(), columns=ohe.get_feature_names_out())
X_U

,Order_1.0,Order_2.0,Order_3.0,Order_4.0,Order_5.0,Order_6.0,Order_7.0,Order_10.0,Order_11.0,Order_12.0,...,NTA_Westchester-Unionport,NTA_Westerleigh,NTA_Williamsbridge-Olinville,NTA_Williamsburg,NTA_Windsor Terrace,NTA_Woodlawn-Wakefield,NTA_Yorkville,NTA_park-cemetery-etc-Bronx,NTA_park-cemetery-etc-Brooklyn,NTA_park-cemetery-etc-Manhattan
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11741,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11742,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11743,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11744,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11745,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

#### Признаков получается неприлично много, поэтому было принято решение от них избавиться

In [27]:
x_cat = (X.dtypes == object).values

In [28]:
X = X[X.columns[~x_cat]]

### 1.3 Baseline

#### Создадим baseline, чтоб потом можно было уидеть насколько сильно выросло качество нашей модели. В качестве baseline возьмем абсолютно обычную линейную регрессию

In [29]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [31]:
lr = LinearRegression().fit(X_train, y_train)

print(f"train loss: {mean_squared_error(y_train, lr.predict(X_train))}")
print(f"test loss: {mean_squared_error(y_test, lr.predict(X_test))}")

train loss: 650.3993451776589
test loss: 1387.8374770642558

## 2. Линейная регрессия

In [32]:
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectFromModel
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

import warnings

warnings.filterwarnings('ignore')

#### Для начала создадим pipeline, в котором мы отшкалируем наши данные, ..., отберем необходимые признаки ну и построим прогноз с L2(???)регуляризацией

In [33]:
pipe = Pipeline(steps=[
    ('scaler', StandardScaler()),
    ('variance', VarianceThreshold(0.01)),
    ('selection', SelectFromModel(Lasso(5.0))),
    ('regressor', Ridge(5.0))
])

pipe.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('variance', VarianceThreshold(threshold=0.01)),
                ('selection', SelectFromModel(estimator=Lasso(alpha=5.0))),
                ('regressor', Ridge(alpha=5.0))])

#### Далее будем подбирать параметры с помощью GridSearchCV

In [34]:
param_grid = {
    'variance__threshold': [1e-12, 1e-11, 1e-10, 1e-09],
    'selection__estimator__alpha': [1e-10, 1e-09, 1e-08],
    'regressor__alpha': [3.0, 3.5, 4.0]
}
grid_search = GridSearchCV(pipe, param_grid, cv=5)

grid_search.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('variance',
                                        VarianceThreshold(threshold=0.01)),
                                       ('selection',
                                        SelectFromModel(estimator=Lasso(alpha=5.0))),
                                       ('regressor', Ridge(alpha=5.0))]),
             param_grid={'regressor__alpha': [3.0, 3.5, 4.0],
                         'selection__estimator__alpha': [1e-10, 1e-09, 1e-08],
                         'variance__threshold': [1e-12, 1e-11, 1e-10, 1e-09]})

{'scaler': StandardScaler(),
'variance': VarianceThreshold(threshold=0.005),
'selection': SelectFromModel(estimator=Lasso(alpha=0.1)),
'regressor': Ridge(alpha=2.0)}

### 1-ый проход:

{'scaler': StandardScaler(),<br/>
 'variance': VarianceThreshold(threshold=0.001),<br/>
 'selection': SelectFromModel(estimator=Lasso(alpha=0.01)),<br/>
 'regressor': Ridge(alpha=2.5)}<br/>
 <br/>
Train: 689.84693344322<br/>
Test: 1112.4461469219423<br/>

### 2-ой проход

{'scaler': StandardScaler(),<br/>
 'variance': VarianceThreshold(threshold=1e-05),<br/>
 'selection': SelectFromModel(estimator=Lasso(alpha=0.0001)),<br/>
 'regressor': Ridge(alpha=4.0)}<br/>
 <br/>
Train: 689.84693344322<br/>
Test: 1112.4461469219423

### 3-ий проход

{'scaler': StandardScaler(),<br/>
 'variance': VarianceThreshold(threshold=1e-07),<br/>
 'selection': SelectFromModel(estimator=Lasso(alpha=1e-06)),<br/>
 'regressor': Ridge(alpha=4.0)}<br/>

<br/>
Train: 688.0822461983004<br/>
Test: 1108.5399232314248

### 4-ый проход

{'scaler': StandardScaler(),<br/>
 'variance': VarianceThreshold(threshold=1e-09),<br/>
 'selection': SelectFromModel(estimator=Lasso(alpha=1e-08)),<br/>
 'regressor': Ridge(alpha=4.0)}<br/>
 <br/>
Train: 688.0822461983004 <br/>
Test: 1108.5399232314248

### 5-ый проход

In [35]:
param_best = grid_search.best_estimator_
param_best.named_steps

{'scaler': StandardScaler(),
 'variance': VarianceThreshold(threshold=1e-12),
 'selection': SelectFromModel(estimator=Lasso(alpha=1e-10)),
 'regressor': Ridge(alpha=4.0)}

In [36]:
param_best.fit(X_train, y_train)
print ("Train: {}".format(mean_squared_error(y_train, param_best.predict(X_train))))
print ("Test: {}".format(mean_squared_error(y_test, param_best.predict(X_test))))

Train: 688.0822461983004
Test: 1108.5399232314248

## 3. Градиентный бустинг

In [37]:
import xgboost as xgb
from xgboost.sklearn import XGBRegressor

In [38]:
model_xgb = XGBRegressor(learning_rate = 0.1,
                         n_estimators = 150,
                         booster='gbtree',
                         importance_type='gain',
                         n_jobs=-1,
                         objective='reg:linear',
                         seed=27)

#### Сделаем baseline для бустинга

In [39]:
model_xgb.fit(X_train, y_train)

print(f"train loss: {mean_squared_error(y_train, model_xgb.predict(X_train))}")
print(f"test loss: {mean_squared_error(y_test, model_xgb.predict(X_test))}")

train loss: 149.9358840802996
test loss: 721967.5219794214

### Подберем гиперпараметры

In [40]:
from sklearn.model_selection import GridSearchCV

param_test1 = {
    'max_depth':[2, 3, 4, 5, 6],
    'min_child_weight':[1e-8, 1e-7, 1e-6, 1e-5]
}

gsearch1 = GridSearchCV(estimator=model_xgb,
                        param_grid=param_test1,
                        scoring='neg_mean_squared_error',
                        n_jobs=-1,
                        cv=5)

gsearch1.fit(X_train, y_train)

gsearch1.best_params_, gsearch1.best_score_

({'max_depth': 4, 'min_child_weight': 1e-08}, -240178.88911544383)

In [41]:
model_xgb.max_depth = 4
model_xgb.min_child_weight = 1e-8

In [42]:
param_test2 = {
    'gamma' : [0, 0.2, 0.4, 0.6, 0.8, 1]
}

gsearch2 = GridSearchCV(estimator=model_xgb,
                        param_grid=param_test2,
                        scoring='neg_mean_squared_error',
                        n_jobs=-1,
                        cv=5)

gsearch2.fit(X_train, y_train)

gsearch2.best_params_, gsearch2.best_score_

({'gamma': 0}, -240178.88911544383)

In [43]:
model_xgb.gamma = 0

In [44]:
param_test3 = {
    'subsample' : [0.6,0.7,0.8,0.9,1.0],
    'colsample_bytree' : [0.6,0.7,0.8,0.9,1.0]
}

gsearch3 = GridSearchCV(estimator=model_xgb,
                        param_grid = param_test3,
                        scoring='neg_mean_squared_error',
                        n_jobs = -1,
                        cv = 5)

gsearch3.fit(X_train, y_train)

gsearch3.best_params_, gsearch3.best_score_

({'colsample_bytree': 1.0, 'subsample': 1.0}, -240178.88911544383)

In [45]:
model_xgb.subsample = 1
model_xgb.colsample_bytree = 1

In [46]:
param_test4 = {
    'reg_alpha' : [1e-5, 1e-4, 1e-3]
}

gsearch4 = GridSearchCV(estimator=model_xgb,
                        param_grid = param_test4,
                        scoring='neg_mean_squared_error',
                        n_jobs = -1,
                        cv = 5)

gsearch4.fit(X_train, y_train)

gsearch4.best_params_, gsearch4.best_score_

({'reg_alpha': 1e-05}, -240178.88911458515)

In [47]:
model_xgb.reg_alpha = 1e-5

In [48]:
model_xgb.fit(X_train, y_train)

print(f"train loss: {mean_squared_error(y_train, model_xgb.predict(X_train))}")
print(f"test loss: {mean_squared_error(y_test, model_xgb.predict(X_test))}")

train loss: 230.14247462996792
test loss: 720717.6052341566

### Уменьшим learning_rate и увеличим n_estimators

In [49]:
model_xgb.learning_rate = 1e-5
model_xgb.n_estimators = 500

In [50]:
model_xgb.fit(X_train, y_train)

print(f"train loss: {mean_squared_error(y_train, model_xgb.predict(X_train))}")
print(f"test loss: {mean_squared_error(y_test, model_xgb.predict(X_test))}")

train loss: 241088.6688083818
test loss: 980.5842916608099